### ISSUE TITLE
Why sign signing key list with the signing key?

### ISSUE THREAD

**Issue by cryptozeb** [scritcash/scrit-whitepaper#6]
https://github.com/scritcash/scrit-whitepaper/blob/9d6812c82d7856acdc06198e691edf051387536e/scrit-whitepaper.md#L144-L149

It's unclear what kind of attack should be mitigated here. If the mint doesn't have the key at all they can't operate any longer, if someone else signs for them the key list signature can be provided by the same entity. At best this protects against the former case caused by implementation errors.

**Comment by JonathanLogan** [comment]
It's an additional protection against key duplication. Duplicating signing keys (either your own or that of others) would allow you to manipulate the quorum rules. It needs to be enforced at every step that a signature refers to and is counted as exactly one mint and one currency-value pair. Otherwise you could add the signature of the mint multiple times to suggest that additional mints have signed. Counting signatures itself is however something that might not work depending on signature algorithm (if the signatures are non-determinisitc, especially when using blind signatures). Hence, key uniqueness needs to be enforced, and this should also means that it should be attributed.

**Comment by calvinfry** [comment]
I took at explaining this in more detail, but I must admin it is still unclear to me how removing the signatures by the DBC signing keys could be exploited in any meaningful way.

The uniqueness of public keys is enforced by the clients  anyway and the self-signature with identity keys establishes a relationship to the mint. I don't see how signing keys could be pushed to another mint involuntarily (then we have bigger problems) and when two mints collude they don't need the same signing key.

But attribution by self-signing with the DBC signing keys certainly doesn't hurt, I just don't see a strong reason for it.

**Comment by JonathanLogan** [comment]
A mint can just copy a signing key from another mint without its cooperation. Attributing which mint took from which other is hard without the self-signature. Concerning the client's uniqueness check: The self-signing just makes unattributable attacks like this much less likely.
