### ISSUE TITLE
Punishment of "bad actors" should be avoided

### ISSUE THREAD

**Issue by cryptozeb** [scritcash/scrit-whitepaper#7]
https://github.com/scritcash/scrit-whitepaper/blob/9d6812c82d7856acdc06198e691edf051387536e/scrit-whitepaper.md#L187-L190

Lightning has a similar approach and it's widely recognized as suboptimal since user or implementation errors can cause big losses. Given that there shouldn't  be a way to defraud the mint anyway, punishment isn't strictly necessary from a game theoretic point of view and should be therefore avoided (it might be relevant for DOS protection, but there are probably other solutions to that problem).

**Comment by JonathanLogan** [comment]
Using a different approach makes spendbook operations more complicated since they need two-phase commits then to prevent race conditions on the spendbook (for both blinding params and for DBCs, not for transaction hashes). This is rather difficult when trying to do sharded storage backends and multiple instances of a mint working on the same spendbook. I consider the use of a simple commit as being less risky for now.

**Comment by calvinfry** [comment]
I reworded the answer from @JonathanLogan into an additional paragraph, I think it makes sense to have the reasoning for simple commits  captured in the whitepaper.
