### ISSUE TITLE
Signing reissue requests

### ISSUE THREAD

**Issue by cryptozeb** [scritcash/scrit-whitepaper#9]
In chapter 4.4 the 0x00 no access control function is mentioned. For centralized chaumian banks that's a sane idea and makes things much easier by not requiring any key exchange. It works because we trust the mint anyway. Once we distribute the mint a problem arises: we don't trust any single mint. So if a reissuance request isn't signed with keys embedded in the DBCs the mint seeing it first could front run, change the destination DBCs and claim the money for themselves.

To mitigate this every DBC needs to commit to a public key. We also don't want to use the same key to avoid correlation of different transactions. The proposed solution is to rely on entropy supplied by the sender which gives them the possibility to embed identifying information. That could be avoided by using bitcoin's HD key generation and giving the sender a fresh xpub from which an arbitrary number of child keys can be derived without giving a way to embed any data.

**Comment by JonathanLogan** [comment]
Since any transaction with a mint requires at least the signatures of that mint for input DBCs AND because the standard transaction only includes those signatures, but not the signatures of other mints, this isn't an issue. A rogue mint would lack the signatures required to execute the transaction on other mints. This comes with two exceptions. Exception one is that the rogue mint got a recovery transaction before at least quorum other mints got a normal transaction. That recovery transaction would include the required signatures. Second, a rogue mint could do a reissue operation at other mints to yield the same output DBC to yield the signatures, and then do his spend transactions to devalidate the original DBC. For this the mint has to expend the value of the DBC himself and he doesn't gain anything.

It would be good if we added to the whitepaper specifically that before any recovery transaction is done with any mint there must be at least quorum normal transactions.
